[phases.setup]
nixPkgs = ["python310", "gcc"]

[phases.install]
cmds = [
  "python -m venv /opt/venv",
  ". /opt/venv/bin/activate",
  "pip install -r requirements.txt"
]

[phases.start]
cmd = "gunicorn -w 4 -b 0.0.0.0:8000 app:app"
